config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'  
  get 'signup', to: 'users#new'
  get 'complete', to: 'purchases#complete'
  get 'confirm', to: 'purchases#confirm'

  resources :users, only: [:show, :create, :edit, :update] do
    member do
      get :purchases
      get :likes
    end
  end
  resources :products, only: [:show]
  resources :purchases, only: [:create]
  resources :likes,only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :purchases
    
    has_many :likes
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :user
  belongs_to :product
  
  validates :quantity, presence: true, numericality: {only_integer: true, less_than: 5}
  validates :payment_method, presence: true,inclusion: {in: %w(代引き クレジットカード)}
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email.downcase! }
    validates :name, presence: true, length: { maximum: 50 }
    validates :email, presence: true, length: { maximum: 255 },
                  format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                  uniqueness: { case_sensitive: false }
    validates :postalcode, presence: true,  format: {with: /\A[0-9]{3}-[0-9]{4}\z/}
    validates :prefecture, presence: true,  length: { maximum: 10 }
    validates :address1, presence: true,  length: { maximum: 100 }
    validates :address2, length: { maximum: 100 }
    validates :tel,  presence: true, numericality: {only_integer: true}, length: { in: 10..11 }
    has_secure_password
    
    has_many :purchases
    
    has_many :likes
    has_many :list_of_likes,through: :likes, source: :product
    
    def like(product)
        self.likes.find_or_create_by(product_id: product.id)
    end

    def unlike(product)
        like = self.likes.find_by(product_id: product.id)
        like.destroy if like
    end

    def liking?(product)
        self.list_of_likes.include?(product)
    end        

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    include SessionsHelper

    private
    
    def require_user_logged_in
        unless logged_in?
          flash[:danger] = 'ログインが必要です。'  
          redirect_to login_url
        end
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
   before_action :require_user_logged_in
  def create
    product = Product.find(params[:product_id])
    current_user.like(product)
    flash[:success] = 'お気に入りを追加しました。'
    redirect_back(fallback_location: root_path)
  end

  def destroy
    product = Product.find(params[:product_id])
    current_user.unlike(product)
    flash[:success] = 'お気に入りを解除しました。'
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def show
    @product = Product.find(params[:id])
    @purchase = Purchase.new
    session[:purchase_product_id]  = @product.id
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :require_user_logged_in
  
  def confirm
    @purchase = Purchase.new(purchase_params)
    @product = Product.find(session[:purchase_product_id] )
    if @purchase.quantity == nil then
      flash.now[:danger]  = '数量を入力してください。'
      render file: "app/views/products/show.html.erb"
    elsif @purchase.quantity < 0 || @purchase.quantity > 4 then
      flash.now[:danger]  = '数量を正しく入力してください。'
      render file: "app/views/products/show.html.erb"
    else
      
    session[:purchase_quantity]  = @purchase.quantity
    end
  end

  def create
    @purchase = current_user.purchases.build(product_id: session[:purchase_product_id], quantity: session[:purchase_quantity], payment_method: purchase_params[:payment_method])
    session[:payment_method] = @purchase.payment_method
    if @purchase.save
      flash[:success] = '購入が完了しました。'
      redirect_to complete_path
    else
      flash[:danger] = '購入が失敗しました。'
      redirect_to complete_path
    end
  end
  
  def complete
    @product = Product.find(session[:purchase_product_id] )
  end
  
  private
  def purchase_params
    params.require(:purchase).permit(:quantity, :payment_method)
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to root_url
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
  
 private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
  
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    @products = Product.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  before_action :require_user_logged_in, only: [:edit, :update, :purchases, :likes]
  before_action :require_user_check, only: [:edit, :update, :purchases, :likes]

  def show
    unless logged_in?
      unless session[:create_user_id].to_s  == params[:id]
        flash[:danger] = 'aaaaa。'  
        redirect_to login_url
      end
      else
        require_user_logged_in
        require_user_check
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = '登録が完了しました。'
      session[:create_user_id]  = @user.id
      redirect_to @user
    else
      flash.now[:danger] = '登録に失敗しました。'
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @user.update(user_params)
      flash[:success] = '更新が完了しました。'
      redirect_to @user
    else
      flash.now[:danger] = '更新に失敗しました。'
      render :edit
    end
  end
  
  def purchases
    @purchases = current_user.purchases.all.order(created_at: :desc).page(params[:page])
  end
  
  def likes
    @likes = current_user.likes.all.order(created_at: :desc).page(params[:page])
  end
  
  def usercomplete
    @user = User.find(session[:create_user_id])
  end  
  
  private

  def user_params
    params.require(:user).permit(:name, :email, :postalcode, :prefecture, :address1, :address2, :tel, :password, :password_confirmation)
  end
  
  def set_user
    @user = User.find(params[:id])
  end
  
  def require_user_check
    unless current_user.id.to_s == params[:id]
      flash[:danger] = '再ログインが必要です。'  
      redirect_to login_url
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-primary">
    <a class="navbar-brand" href="/">COMPANY　LOGO</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <% if logged_in? %>
          <li class="nav-item"><%= link_to '購入履歴', purchases_user_path(current_user), class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'お気に入り', likes_user_path(current_user), class: 'nav-link' %></li>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><%= current_user.name %></a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li class="dropdown-item"><%= link_to 'ユーザ情報', user_path(current_user) %></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to 'ログアウト', logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
        <li class="nav-item"><%= link_to '会員登録', signup_path, class: 'nav-link' %></li>
        <li class="nav-item"><%= link_to 'ログイン', login_path, class: 'nav-link' %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html  lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>WebService</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/likes/_like_button.html.erb
<% if current_user.liking?(product) %>
    <%= form_with(model: current_user.likes.find_by(product_id: product.id), local: true, method: :delete) do |f| %>
        <%= hidden_field_tag :product_id, product.id, id:"No_#{i}"  %>
        <%= f.submit 'お気に入り解除', class: 'btn btn-secondary btn-block' %>
    <% end %>
<% else %>
    <%= form_with(model: current_user.likes.build, local: true) do |f| %>
        <%= hidden_field_tag :product_id, product.id, id:"No_#{i}"  %>
        <%= f.submit 'お気に入り', class: 'btn btn-outline-secondary btn-block' %>
    <% end %>
<% end %>

app/views/products/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-5">
            <%= image_tag @product.image, class: "img-fluid",alt: "" %>
        </div>
        <div class="col-md-7">
            <p><%= @product.name %><br>
            <%= @product.description %><br></p>
            <p class= "text-right"><%= @product.price %>円</p>
            
            <%= form_with(model: @purchase, local: true, method: "GET", url: confirm_path)  do |f| %>
            <%= render 'layouts/error_messages', model: f.object %>
            <div class="form-group">
                <p class="text-right"><%= f.select  :quantity,  [["1", 1], ["2", 2], ["3", 3], ["4", 4]], include_blank: "個数を選択"  %>　個</p>
            </div>
                <%= f.submit '購入手続き', class: 'btn btn-danger btn-block' %><br>
                <% end %>
                <% if logged_in? %>
                    <%= render 'likes/like_button', product: @product, i:0 %>
                <% end %>
        </div>
    </div>
</div>

app/views/purchases/complete.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-4">
            
            <h5>お届け先</h5>
            <div class="offset-sm-1">
                <p><%= current_user.name %><br>
                〒<%= current_user.postalcode %><br>
                <%= current_user.prefecture %><%= current_user.address1 %><%= current_user.address2 %></p>
            </div>
        </div>
        <div class="col-md-4">
            <h5>お支払方法</h5>
            <p><%= session[:payment_method] %></p>
        </div>
        <div class="col-md-4">
            <br><p class = "text-right"><strong>合計：<%= @product.price * session[:purchase_quantity] %>円</strong></p>
        </div>
        <div class="col-md-12">
        <h5>ご注文商品</h5>
        </div>
        <div class="col-md-6">
                <%= image_tag @product.image, class: "img-fluid",alt: "" %>
        </div>
        <div class="col-md-6">
            <table class="table">
                <thead>
                    <tr><td colspan="2"><%= @product.name %></td></tr>
                    <tr><td colspan="2"><%= @product.description %></td></tr>
                    <tr><td>値段</td>
                        <td><div class="text-right"><%= @product.price %>円</div></td>
                    </tr>
                    <tr>
                        <td>個数</td>
                        <td><div class="text-right"><%= session[:purchase_quantity] %>個</div></td>
                    </tr>
                    <tr>
                        <td>合計</td>
                        <td><div class="text-right"><%= @product.price * session[:purchase_quantity] %>円</div></td>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</div>
<div class="text-right">
    <a href="<%= root_path %>" class="btn btn-outline-secondary">トップページ</a>
</div>

app/views/purchases/confirm.html.erb
<%= form_with(model: @purchase, local: true)  do |f| %>
<div class="container">
    <div class="row">
        <div class="col-md-4">
            
            <h5>お届け先</h5>
            <div class="offset-sm-1">
                <p>お名前：<%= current_user.name %><br>
                住所　：〒<%= current_user.postalcode %><br>
                <%= current_user.prefecture %><%= current_user.address1 %><%= current_user.address2 %></p>
            </div>
        </div>
        <div class="col-md-4">
            <h5>お支払方法</h5>
            <div class="offset-sm-1">
                <div class="form-group">
                    <p><%= f.select  :payment_method,  [["代引き", "代引き"], ["クレジットカード", "クレジットカード"]]  %></p>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <%= f.submit '購入する', class: 'btn btn-danger btn-block' %>
            <%# 個数の掛け算 %>
            <br><p class = "text-right"><strong>合計：<%= @product.price * @purchase.quantity %>円</strong></p>
        </div>
        <div class="col-md-12">
        <h5>ご注文商品</h5>
        </div>
        <div class="col-md-6">
                <%= image_tag @product.image, class: "img-fluid", alt: "" %>
        </div>
        <div class="col-md-6">
            <table class="table">
                <thead>
                    <tr><td colspan="2"><%= @product.name %></td></tr>
                    <tr><td colspan="2"><%= @product.description %></td></tr>
                    <tr><td>値段</td>
                        <td><div class="text-right"><%= @product.price %>円</div></td>
                    </tr>
                    <tr>
                        <td>個数</td>
                        <td><div class="text-right"><%= @purchase.quantity %>個</div></td>
                    </tr>
                    <tr>
                        <td>合計</td>
                        <td><div class="text-right"><%= @product.price * @purchase.quantity %>円</div></td>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</div>
<% end %>

app/views/toppages/index.html.erb
<% if @products.any? %>
  <div class="container">
    <div class="row">
      <% @products.each do |product| %>
        <div class="col-md-3">
          <div class="card mb-3 shadow-sm">
            <%= link_to image_tag(product.image, class: "img-fluid", alt: ""), product_path(product)  %>
            <div class="card-body">
              <p class="card-text"><%= product.name %><br><%= product.price %>円</p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<div class="row">
  <div class="col-sm-6 offset-sm-3">
    <%= form_with(model: user, local: true) do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
      
    <div class="form-group">
      <%= f.label :name, 'お名前' %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :email, 'メールアドレス' %>
      <%= f.email_field :email, class: 'form-control' %>
    </div>
      
    <h5>お届け先</h5>
    <div class="form-group">
      <%= f.label :postalcode, '郵便番号(数字のみ)' %>
      <%= f.text_field :postalcode, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :prefecture, '都道府県' %>
      <%= f.text_field :prefecture, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :address1, '市区町村・番地' %>
      <%= f.text_field :address1, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :address2, 'マンション名・部屋番号（任意）' %>
      <%= f.text_field :address2, class: 'form-control' %>
    </div>
      
    <div class="form-group">
      <%= f.label :tel, '電話番号(数字のみ)' %>
      <%= f.telephone_field :tel, class: 'form-control' %>
    </div>      
      
    <% if logged_in? %>
     <div class="text-right">
       <%= f.submit '更新する', class: 'btn btn-primary btn-lg' %>
     </div>
    <% else %>
        <div class="form-group">
          <%= f.label :password, 'パスワード' %>
          <%= f.password_field :password, class: 'form-control' %>
        </div>
  
        <div class="form-group">
          <%= f.label :password_confirmation, 'パスワード（確認用）' %>
          <%= f.password_field :password_confirmation, class: 'form-control' %>
        </div>
        
        <div class="text-right">
          <%= f.submit '登録する', class: 'btn btn-primary btn-lg' %>
        </div>
      <% end %>
    <% end %>
  </div>      
</div>    

app/views/users/edit.html.erb
<%= render 'form', user: @user %>

app/views/users/likes.html.erb
<% if @likes.any? %>
  <% i = 0 %>
  <% @likes.each do |like| %>
    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <%= image_tag like.product.image, class: "img-fluid",alt: "" %>
        </div>
        <div class="col-md-4">
            <table class="table">
              <thead>
                  <tr><td colspan="2"><%= like.product.name %></td></tr>
                  <tr><td colspan="2"><%= like.product.description %></td></tr>
                  <tr><td>値段</td>
                      <td><div class="text-right"><%= like.product.price %>円</div></td>
                  </tr>
              </thead>
          </table>

        </div>
        <div class="col-md-4">
          <a href="<%= product_path(like.product) %>" class="btn btn-danger btn-block">購入する</a><br>
          <%= render 'likes/like_button', product: like.product, i: i %>
        </div>
      </div>
    </div>
  <% i += 1 %>
  <% end %>
  <%= paginate @likes %>
  <% else %>
    <div class="alert alert-warning" role="alert">お気に入りがありません。</div>
<% end %>

app/views/users/new.html.erb
<%= render 'form', user: @user %>

app/views/users/purchases.html.erb
<% if @purchases.any? %>
  <% i = 0 %>
    <% @purchases.each do |purchase| %>
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <h5>購入日：<%= purchase.created_at.in_time_zone('Tokyo').strftime("%Y年%m月%d日")  %></h5>
          </div>
          <div class="col-md-4">
            <%= image_tag purchase.product.image, class: "img-fluid",alt: "" %>
          </div>
          <div class="col-md-4">
              <table class="table">
                <thead>
                    <tr><td colspan="2"><%= purchase.product.name %></td></tr>
                    <tr><td colspan="2"><%= purchase.product.description %></td></tr>
                    <tr><td>値段</td>
                        <td><div class="text-right"><%= purchase.product.price %>円</div></td>
                    </tr>
                    <tr>
                        <td>個数</td>
                        <td><div class="text-right"><%= purchase.quantity %>個</div></td>
                    </tr>
                    <tr>
                        <td>合計</td>
                        <td><div class="text-right"><%= purchase.product.price * purchase.quantity %>円</div></td>
                    </tr>
                </thead>
            </table>

          </div>
          <div class="col-md-4">
            <a href="<%= product_path(purchase.product) %>" class="btn btn-danger btn-block">購入する</a><br>
            <%= render 'likes/like_button', product: purchase.product, i: i %>
          </div>
        </div>
      </div>
    <% i += 1 %>
    <% end %>
  <%= paginate @purchases %>
  <% else %>
  <div class="alert alert-warning" role="alert">購入履歴がありません。</div>
<% end %>

app/views/users/show.html.erb
<div class="row">
  <div class="col-sm-6 offset-sm-3">
      <h6>お名前</h6>
      <div class="offset-sm-1">
      <p><%= @user.name %></p>
      </div>
      <h6>メールアドレス</h6>
      <div class="offset-sm-1">
      <p><%= @user.email %></p>
      </div>
      <h6>お届け先</h6>
      <div class="offset-sm-1">
      <p>〒<%= @user.postalcode %></p>
      </div>
      <div class="offset-sm-1">
      <p><%= @user.prefecture %><%= @user.address1 %><%= @user.address2 %></p>
      </div>
      <h6>電話番号</h6>
      <div class="offset-sm-1">
      <p><%= @user.tel %></p>
      </div>
      <div class="text-right">
      <% if logged_in? %>
      <a href="<%= edit_user_path %>" class="btn btn-primary btn-lg">更新する</a>
      <% else %>
      <a href="<%= login_path %>" class="btn btn-primary btn-lg">ログイン</a>
      <% end %>
      </div>  
    </div>
</div>